# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-15 11:01
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('amount', models.BigIntegerField()),
                ('expiration_time', models.DateTimeField(default=datetime.datetime(2120, 8, 22, 15, 31, 18, 555714))),
                ('active', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.BigIntegerField(blank=True, null=True)),
                ('authority', models.CharField(max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 9, 15, 15, 31, 18, 559904), editable=False)),
                ('status', models.NullBooleanField()),
                ('ref_id', models.CharField(max_length=50, null=True)),
                ('send_receipt', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='payments.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('family', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('father_name', models.CharField(max_length=200, null=True)),
                ('code_meli', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Meli code must be entered in the format: 'XXXXXXXXXX'. only 10 digits allowed.", regex='^\\d{10}$')])),
                ('code_shenasname', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: \'09XXXXXXXXX\'. "09" than 9 digit digits allowed.', regex='^09\\d{9}$')])),
                ('phone_number2', models.CharField(max_length=15, null=True)),
                ('origin_town', models.CharField(max_length=200, null=True)),
                ('birthday', models.DateField(null=True)),
                ('address', models.TextField(max_length=2000, null=True)),
                ('payment_type', models.CharField(choices=[('0', '\u0646\u0642\u062f\u06cc'), ('1', '\u0627\u0642\u0633\u0627\u0637')], default='0', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('price', models.BigIntegerField()),
                ('active', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('family', models.CharField(max_length=200)),
                ('code_meli', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message="Meli code must be entered in the format: 'XXXXXXXXXX'. only 10 digits allowed.", regex='^\\d{10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payments.Product')),
                ('class_type', models.CharField(choices=[('R', 'regular'), ('I', 'intensive')], max_length=1)),
                ('time', models.CharField(choices=[('912', '9-12'), ('1316', '13-16'), ('1720', '17-20')], max_length=4)),
                ('day', models.CharField(choices=[('STW', 'SA-WE'), ('STT', 'SA-TH'), ('E', 'even'), ('O', 'odd')], max_length=4)),
                ('show', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='payments.Teacher')),
            ],
            bases=('payments.product',),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_info', to='payments.PaymentInformation'),
        ),
        migrations.AddField(
            model_name='discount',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.ManyToManyField(to='payments.Discount'),
        ),
        migrations.AddField(
            model_name='cart',
            name='verification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SMS.Verify'),
        ),
        migrations.AddField(
            model_name='cart',
            name='course',
            field=models.ManyToManyField(to='payments.Course'),
        ),
    ]
