# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-15 12:53
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200915_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2120, 8, 22, 17, 23, 25, 433813)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 17, 23, 25, 438531), editable=False),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='address',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='code_meli',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Meli code must be entered in the format: 'XXXXXXXXXX'. only 10 digits allowed.", regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='family',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='origin_town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paymentinformation',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
