# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-15 13:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20200915_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='course',
            field=models.ManyToManyField(blank=True, to='payments.Course'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.ManyToManyField(blank=True, to='payments.Discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2120, 8, 22, 17, 45, 38, 556830)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 17, 45, 38, 562068), editable=False),
        ),
    ]
