# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-11 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_auto_20200921_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2120, 9, 17, 16, 17, 15, 441811)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 17, 15, 447143), editable=False),
        ),
    ]
