# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-10 13:02
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0014_auto_20201011_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentInformation',
            new_name='PersonalInformation',
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'permissions': (('CAN_VIEW_Payment', 'Can View Payment'),)},
        ),
        migrations.RemoveField(
            model_name='cart',
            name='payment_info',
        ),
        migrations.AddField(
            model_name='cart',
            name='personal_info_old',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_info', to='payments.PersonalInformation'),
        ),
        migrations.AddField(
            model_name='payment',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='register_operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='personal_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_info', to='payments.PersonalInformation'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_type',
            field=models.CharField(choices=[('R', 'regular'), ('I', 'intensive'), ('S', 'special')], max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='day',
            field=models.CharField(choices=[('STW', 'SA-WE'), ('STT', 'SA-TH'), ('E', 'even'), ('O', 'odd'), ('TH', 'TH')], max_length=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(choices=[('912', '9-12'), ('1316', '13-16'), ('1720', '17-20'), ('1420', '14-20')], max_length=4),
        ),
        migrations.AlterField(
            model_name='discount',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2120, 10, 17, 16, 32, 30, 277923)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 16, 32, 30, 283006), editable=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='ref_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
