# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-10 13:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_auto_20201110_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2120, 10, 17, 16, 34, 37, 732506)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 10, 16, 34, 37, 738637), editable=False),
        ),
    ]
