# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-16 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0004_auto_20200915_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sent',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 13, 40, 58, 723612), editable=False),
        ),
        migrations.AlterField(
            model_name='sent',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'بررسی نشده'), ('1', 'در صف ارسال قرار دارد'), ('2', 'زمان بندی شده (ارسال در تاریخ معین)'), ('4', 'ارسال شده به مخابرات'), ('5', 'ارسال شده به مخابرات'), ('6', 'خطا در ارسال پیام که توسط سر شماره پیش می آید و به معنی عدم رسیدن پیامک می\u200cباشد'), ('10', 'رسیده به گیرنده'), ('11', 'نرسیده به گیرنده ، این وضعیت به دلایلی از جمله خاموش یا خارج از دسترس بودن گیرنده اتفاق می افتد'), ('13', 'ارسال پیام از سمت کاربر لغو شده یا در ارسال آن مشکلی پیش آمده که هزینه آن به حساب برگشت داده می\u200cشود'), ('14', 'بلاک شده است، عدم تمایل گیرنده به دریافت پیامک از خطوط تبلیغاتی که هزینه آن به حساب برگشت داده می\u200cشود'), ('100', 'شناسه پیامک نامعتبر است')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='verify',
            name='expiration_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 16, 13, 45, 58, 724234), editable=False),
        ),
        migrations.AlterField(
            model_name='verify',
            name='token1',
            field=models.CharField(default='823', max_length=3),
        ),
        migrations.AlterField(
            model_name='verify',
            name='token2',
            field=models.CharField(default='655', max_length=3),
        ),
    ]
