# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-21 14:21
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 9, 21, 17, 51, 7, 247784), editable=False)),
                ('created_date_jalali', models.CharField(default='1399-06-31 17:51:07', editable=False, max_length=50)),
                ('created_date_jalali_str', models.CharField(default='Doshanbeh 31 Shahrivar 1399 17:51:07', editable=False, max_length=50)),
                ('approved_comment', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime(2020, 9, 21, 17, 51, 7, 249042), editable=False)),
                ('created_date_jalali', models.CharField(default='1399-06-31 17:51:07', editable=False, max_length=50)),
                ('created_date_jalali_str', models.CharField(default='Doshanbeh 31 Shahrivar 1399 17:51:07', editable=False, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabelDefinition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=500, null=True)),
                ('color_code', models.CharField(choices=[('FF0000', 'Red'), ('FFA500', 'Orange'), ('800000', 'Maroon'), ('808000', 'Olive'), ('800080', 'Purple'), ('FF00FF', 'Pink'), ('008080', 'Teal'), ('0000FF', 'Blue'), ('000080', 'Navy'), ('000000', 'Black'), ('808080', 'Gray')], default='000000', max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_family', models.CharField(default='No Name', max_length=500)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True)),
                ('phone_number', models.CharField(default='09000000000', max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '09999999999'. Up to 15 digits allowed.", regex='^[0-9].{6,15}$')])),
                ('register_status', models.CharField(choices=[('K', 'OK'), ('C', 'Cancel'), ('D', 'Default')], default='D', max_length=1)),
                ('led_time', models.DateTimeField(default=datetime.datetime(2020, 9, 21, 17, 51, 7, 245799), editable=False)),
                ('led_time_jalali', models.CharField(default='1399-06-31 17:51:07', editable=False, max_length=50)),
                ('led_time_jalali_str', models.CharField(default='Doshanbeh 31 Shahrivar 1399 17:51:07', editable=False, max_length=50)),
                ('question', models.TextField(blank=True, default='')),
                ('operator', models.ManyToManyField(editable=False, related_name='operator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='No Name', max_length=100)),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('token_activation', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='origin',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.Origin'),
        ),
        migrations.AddField(
            model_name='lead',
            name='registered_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.LabelDefinition'),
        ),
        migrations.AddField(
            model_name='label',
            name='owner',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='label',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.Lead'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leads.Lead'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set([('post', 'label')]),
        ),
    ]
