# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-04 09:10
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_and_family', models.CharField(default='VALUE_IS_NULL', max_length=500)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1, null=True)),
                ('phone_number', models.CharField(default='VALUE_IS_NULL', max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, default='VALUE_IS_NULL@NULL.NULL', max_length=254, null=True)),
                ('register_status', models.CharField(choices=[('K', 'OK'), ('N', 'Cancel')], default='N', max_length=1, null=True)),
                ('led_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('discription', models.TextField(default='VALUE_IS_NULL', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
