# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-09-21 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 18, 1, 50, 271736), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date_jalali',
            field=models.CharField(default='1399-06-31 18:01:50', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date_jalali_str',
            field=models.CharField(default='Doshanbeh 31 Shahrivar 1399 18:01:50', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 18, 1, 50, 273114), editable=False),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_date_jalali',
            field=models.CharField(default='1399-06-31 18:01:50', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_date_jalali_str',
            field=models.CharField(default='Doshanbeh 31 Shahrivar 1399 18:01:50', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='led_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 18, 1, 50, 269654), editable=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='led_time_jalali',
            field=models.CharField(default='1399-06-31 18:01:50', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='led_time_jalali_str',
            field=models.CharField(default='Doshanbeh 31 Shahrivar 1399 18:01:50', editable=False, max_length=50),
        ),
    ]
