# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-10-11 12:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20200921_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 17, 15, 263398), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date_jalali',
            field=models.CharField(default='1399-07-20 16:17:15', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date_jalali_str',
            field=models.CharField(default='Yekshanbeh 20 Mehr 1399 16:17:15', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 17, 15, 264780), editable=False),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_date_jalali',
            field=models.CharField(default='1399-07-20 16:17:15', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_date_jalali_str',
            field=models.CharField(default='Yekshanbeh 20 Mehr 1399 16:17:15', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='led_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 11, 16, 17, 15, 261084), editable=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='led_time_jalali',
            field=models.CharField(default='1399-07-20 16:17:15', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='led_time_jalali_str',
            field=models.CharField(default='Yekshanbeh 20 Mehr 1399 16:17:15', editable=False, max_length=50),
        ),
    ]
