# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-04 10:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_auto_20190904_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='discription',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name_and_family',
            field=models.CharField(default='No Name', max_length=500),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone_number',
            field=models.CharField(default='09000000000', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='register_status',
            field=models.CharField(choices=[('K', 'OK'), ('C', 'Cancel'), ('D', 'Default')], default='D', max_length=1),
        ),
    ]
