# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-04 10:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20190904_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='led_time',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
