# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-04 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20190904_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='leads.Token'),
        ),
    ]
