# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-04 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20190904_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
    ]
