# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-07 10:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20190904_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='discription',
            new_name='description',
        ),
    ]
