# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-07 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20190907_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
