# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-11-11 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_auto_20201110_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 10, 43, 35, 648294), editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date_jalali',
            field=models.CharField(default='1399-08-21 10:43:35', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date_jalali_str',
            field=models.CharField(default='Chaharshanbeh 21 Aban 1399 10:43:35', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 10, 43, 35, 650349), editable=False),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_date_jalali',
            field=models.CharField(default='1399-08-21 10:43:35', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='label',
            name='created_date_jalali_str',
            field=models.CharField(default='Chaharshanbeh 21 Aban 1399 10:43:35', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='led_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 11, 10, 43, 35, 644724), editable=False),
        ),
        migrations.AlterField(
            model_name='lead',
            name='led_time_jalali',
            field=models.CharField(default='1399-08-21 10:43:35', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='led_time_jalali_str',
            field=models.CharField(default='Chaharshanbeh 21 Aban 1399 10:43:35', editable=False, max_length=50),
        ),
    ]
